---
description: "#{repo}"
builds:
- platform: "alpine"
  arch: "amd64"
  asset_filename: "#{repo}_#{version}_ruby-2.7.6_alpine_linux_amd64.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  -  "entity.system.os == 'linux'"
  -  "entity.system.arch == 'amd64'"
  -  "entity.system.platform == 'alpine'"
  -  "entity.system.platform_version.split('.')[0] == '3'"
- platform: "debian"
  arch: "amd64"
  asset_filename: "#{repo}_#{version}_ruby-2.7.6_debian_linux_amd64.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  -  "entity.system.os == 'linux'"
  -  "entity.system.arch == 'amd64'"
  -  "entity.system.platform_family == 'debian'"
- platform: "centos6"
  arch: "amd64"
  asset_filename: "#{repo}_#{version}_ruby-2.7.6_centos6_linux_amd64.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  -  "entity.system.os == 'linux'"
  -  "entity.system.arch == 'amd64'"
  -  "entity.system.platform != 'amazon'"
  -  "entity.system.platform_family == 'rhel'"
  -  "parseInt(entity.system.platform_version.split('.')[0]) == 6"
- platform: "centos7"
  arch: "amd64"
  asset_filename: "#{repo}_#{version}_ruby-2.7.6_centos7_linux_amd64.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  -  "entity.system.os == 'linux'"
  -  "entity.system.arch == 'amd64'"
  -  "entity.system.platform != 'amazon'"
  -  "entity.system.platform_family == 'rhel'"
  -  "parseInt(entity.system.platform_version.split('.')[0]) == 7"
- platform: "centos8"
  arch: "amd64"
  asset_filename: "#{repo}_#{version}_ruby-2.7.6_centos8_linux_amd64.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  -  "entity.system.os == 'linux'"
  -  "entity.system.arch == 'amd64'"
  -  "entity.system.platform != 'amazon'"
  -  "entity.system.platform_family == 'rhel'"
  -  "parseInt(entity.system.platform_version.split('.')[0]) == 8"
- platform: "amzn1"
  arch: "amd64"
  asset_filename: "#{repo}_#{version}_ruby-2.7.6_amzn1_linux_amd64.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  -  "entity.system.os == 'linux'"
  -  "entity.system.arch == 'amd64'"
  -  "entity.system.platform == 'amazon'"
  -  "entity.system.platform_version.split('.')[0] == '2018'"
- platform: "amzn2"
  arch: "amd64"
  asset_filename: "#{repo}_#{version}_ruby-2.7.6_amzn2_linux_amd64.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  -  "entity.system.os == 'linux'"
  -  "entity.system.arch == 'amd64'"
  -  "entity.system.platform == 'amazon'"
  -  "entity.system.platform_version.split('.')[0] == '2'"
